### ISSUE TITLE
[STORY] (어드민) 유저 추가(슈퍼 어드민 아님)

### ISSUE THREAD

**Issue by RebirthLee** [StockfolioOfficial/back-editfolio#1]
## 업무 설명
어드민 유저 추가(슈퍼어드민 아님)
- 데이터
  - 이메일
  - 비밀번호(bcrypt)
  - 이름
  - 닉네임(별칭)
## TODO
- [ ] validate(데이터 검증)
  - [ ] 이메일
  - [ ] 비밀번호 8자 이상 32자이하(영문 숫자 조합 필수, 특수문자 가능)
  - [ ] 이름 2자이상 60자이하
  - [ ] 닉네임 2자이상 60자이하
  - [ ] role is ADMIN
- [ ] HTTTP Status 201
- [ ] Response, id return
- [ ] swagger doc
