### ISSUE TITLE
[STORY] 주문 모델링

### ISSUE THREAD

**Issue by hollibleling** [StockfolioOfficial/back-editfolio#18]
## 업무 설명
주문 테이블 생성
## TODO
- [ ] order 테이블 생성
- [ ] memo column 생성
- [ ] due_date, assignee, memo nullable 옵션 추가
