### ISSUE TITLE
[STORY] 고객 유저 추가 기능 부족한 부분 마무리

### ISSUE THREAD

**Issue by RebirthLee** [StockfolioOfficial/back-editfolio#2]
## 업무 설명
기존에 유저 추가하는 기능에다.  
`//todo` 작성을 해두었지만 다시 적습니다.  
`customer` 테이블이 적용되지 않는 상태여서 유저 고객 정보의 디테일한 정보를 삽입하는 부분 추가
## TODO
- [ ] `customer` 엔티티(도메인) 추가
- [ ] `user usecase`내에서 `customer` 엔티티 insert 및 받은 데이터 저장 기능
- [ ] http interface 쪽은 이미 설계상 건들게 없음. (주의)
  - [ ] http body에 데이터를 추가적으로 받는 행위
